let products = [
  {
    product__image: "./potato.jpeg",
    product__offer: "10% OFF",
    product__sourced: "sourced at : 5am",
    product__name: "Aloo",
    product__weight: "1Kg",
    product__newPrice: "15",
    product__oldPrice: "20",
    count: 0,
  },
  {
    product__image: "./potato.jpeg",
    product__offer: "10% OFF",
    product__sourced: "sourced at : 5am",
    product__name: "Aloo",
    product__weight: "1Kg",
    product__newPrice: "15",
    product__oldPrice: "20",
    count: 0,
  },
  {
    product__image: "./potato.jpeg",
    product__offer: "10% OFF",
    product__sourced: "sourced at : 5am",
    product__name: "Aloo",
    product__weight: "1Kg",
    product__newPrice: "15",
    product__oldPrice: "20",
    count: 0,
  },
  {
    product__image: "./potato.jpeg",
    product__offer: "10% OFF",
    product__sourced: "sourced at : 5am",
    product__name: "Aloo",
    product__weight: "1Kg",
    product__newPrice: "15",
    product__oldPrice: "20",
    count: 0,
  },
  {
    product__image: "./potato.jpeg",
    product__offer: "10% OFF",
    product__sourced: "sourced at : 5am",
    product__name: "Aloo",
    product__weight: "1Kg",
    product__newPrice: "15",
    product__oldPrice: "20",
    count: 0,
  },
  {
    product__image: "./potato.jpeg",
    product__offer: "10% OFF",
    product__sourced: "sourced at : 5am",
    product__name: "Aloo",
    product__weight: "1Kg",
    product__newPrice: "15",
    product__oldPrice: "20",
    count: 0,
  },
  {
    product__image: "./potato.jpeg",
    product__offer: "10% OFF",
    product__sourced: "sourced at : 5am",
    product__name: "Aloo",
    product__weight: "1Kg",
    product__newPrice: "15",
    product__oldPrice: "20",
    count: 0,
  },
  {
    product__image: "./potato.jpeg",
    product__offer: "10% OFF",
    product__sourced: "sourced at : 5am",
    product__name: "Aloo",
    product__weight: "1Kg",
    product__newPrice: "15",
    product__oldPrice: "20",
    count: 0,
  },
  {
    product__image: "./potato.jpeg",
    product__offer: "10% OFF",
    product__sourced: "sourced at : 5am",
    product__name: "Aloo",
    product__weight: "1Kg",
    product__newPrice: "15",
    product__oldPrice: "20",
    count: 0,
  },
];

export default products;
