export const INCREMENT_COUNT = "INCREMENT_COUNT";

export const DECREMENT_COUNT = "DECREMENT_COUNT";

export const DISPLAY_COUNTER = "DISPLAY_COUNTER";

export const CHANGE_CATEGORY = "CHANGE_CATEGORY";

export const CHANGE_PRODUCT_CATEGORY = "CHANGE_PRODUCT_CATEGORY";
